# Generated by Django 5.0.7 on 2025-10-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('encounter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('encounter_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('effective_time', models.DateTimeField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('medication_code', models.CharField(max_length=50)),
                ('dose_mg', models.FloatField()),
                ('frequency_per_day', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('lab_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('result_value', models.FloatField()),
                ('reference_low', models.FloatField()),
                ('reference_high', models.FloatField()),
                ('collected_time', models.DateTimeField()),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider'),
        ),
    ]
