name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: health
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install backend deps
        run: pip install -r backend/requirements.txt
      - name: Django checks
        run: cd backend && python manage.py check
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Frontend build
        run: |
          cd frontend
          npm ci
          npm run build
