name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Frontend install
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Backend check
        run: |
          python3 -V || true
      - name: Webpack test build
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm run build || true; fi
